config/routes.rb
Rails.application.routes.draw do

  root to: "site#index"
  resources :pokemons, only: [:new, :create, :show]
  resources :users, except: [:index, :edit, :update]
  resources :caught_pokemons, only: [:create, :show, :destroy]
  resources :site, only: [:index, :about, :map]
  resources :sessions, only: [:create]

  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"

  get "/about", to: "site#about"
  get "/map", to: "site#map"
  get "/battle", to: "pokemon#show"
  post "/mapstate", to: "mapstates#create"
  get "/mapstate", to: "mapstates#index"
  post "/user_question_type", to: "user_question_types#create"
  get "/user_question_type", to: "user_question_types#index"

end

app/models/caught_pokemon.rb
class CaughtPokemon < ActiveRecord::Base

  belongs_to :user
  belongs_to :pokemon

  validates :name, presence: true
end

app/models/pokemon.rb
class Pokemon < ActiveRecord::Base

  has_many :caught_pokemons
  has_many :users, through: :caught_pokemons

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :caught_pokemons, dependent: :destroy
  has_many :pokemons, through: :caught_pokemons

  validates :username, 
            presence: true,
            uniqueness: true,
            length: {minimum: 6}

end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to "/login" unless current_user
  end
  
end

app/controllers/caught_pokemon_controller.rb
class CaughtPokemonController < ApplicationController
  def create
    @caught_pokemon = CaughtPokemon.new(caught_pokemon_params)
    if @caught_pokemon.save
      redirect_to caught_pokemon_path(@caught_pokemon)
    else
      flash[:error] = @caught_pokemon.errors.full_messages.join(', ')
      redirect_to root_path
    end
  end

  def show
  end

  def destroy
  end

  private

  def caught_pokemon_params
    params.require(:caught_pokemon).permit(:name, :user_id, :pokemon_id)
  end
end

app/controllers/caught_pokemons_controller.rb
class CaughtPokemonsController < ApplicationController
  before_action :authorize
  before_action :set_pokemon, only:[:show,:destroy]
  
  def create
    caught_pokemon = CaughtPokemon.new(caught_pokemon_params)
    pokemon = Pokemon.find_by_national_id(caught_pokemon_params[:national_id])
    if current_user.pokemons.include?(pokemon)
      flash[:error] = "You can only have one of each species of pokemon!"
      redirect_to map_path
    else
      caught_pokemon.save
      flash[:notice] = "New pokemon in your pokedex!"
      redirect_to map_path
    end
  end

  def show
    @pokemon = Pokemon.find_by_id(@caught_pokemon.pokemon_id);
  end

  def destroy
    if @caught_pokemon.user_id == current_user.id
      @caught_pokemon.destroy
      flash[:notice] = "You let your best friend go."
      redirect_to user_path(current_user)
    else
      redirect_to user_path(current_user)
      flash[:error] = "Not your pokemon!"
    end
  end

  private

  def set_pokemon
    @caught_pokemon = CaughtPokemon.find(params[:id]);
  end

  def caught_pokemon_params
    params.require(:caught_pokemon).permit(:name, :user_id, :pokemon_id, :national_id)
  end
end

app/controllers/mapstates_controller.rb
require 'json'

class MapstatesController < ApplicationController

  def index
    #session variable sets the key :map_state to the data passed through from ajax call
    #'should' be working, theres a 200 response with the data as string in the logs
    if session[:map_state]
      render json: { map_state: session[:map_state]}
    else
      render json: { initialize_map: true }
    end
  end
  
  def create
    session[:map_state] = JSON.parse(params[:data_value])
    render json: session[:map_state]
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  
  def new
  end

  def show
    if params[:id].to_i > ENV['MAX_POKEMON_ID'].to_i
      redirect_to map_path
    else
      @caught_pokemon = CaughtPokemon.new
      
      # if it is in the database, get from the database
      if @pokemon = Pokemon.find_by_national_id(params[:id])

      # otherwise get from the api
      else
        new_pokemon = Pokegem.get "pokemon", params[:id]
        parsed_pokemon = ActiveSupport::JSON.decode(new_pokemon)
        type2 = parsed_pokemon["types"][1] ? parsed_pokemon["types"][1]["name"] : nil
        evolve_to = parsed_pokemon["evolutions"][0] ? parsed_pokemon["evolutions"][0]["name"] : nil
        @pokemon = Pokemon.new({
                                  national_id: parsed_pokemon["national_id"],
                                  species: parsed_pokemon["name"],
                                  pokemon_type1: parsed_pokemon["types"][0]["name"],
                                  pokemon_type2: type2,
                                  evolution: evolve_to,
                                  attack: parsed_pokemon["attack"],
                                  defense: parsed_pokemon["defense"],
                                  sp_attack: parsed_pokemon["sp_atk"],
                                  sp_defense: parsed_pokemon["sp_def"],
                                  speed: parsed_pokemon["speed"],
                                  sprite: "",
                                  catch_rate: 0
                                })
        @pokemon.sprite += @pokemon.national_id.to_s + ".png"
        @pokemon.catch_rate = 600 - @pokemon.attack
        @pokemon.catch_rate -= @pokemon.defense
        @pokemon.catch_rate -= @pokemon.sp_attack
        @pokemon.catch_rate -= @pokemon.sp_defense
        @pokemon.catch_rate -= @pokemon.speed
        @pokemon.save
      end
    end
  end

  def create
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 
  def new
  end

  def create
    @user = User.find_by_username(user_params[:username])
    if @user && @user.authenticate(user_params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(current_user)
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:map_state] = nil
    session[:user_id] = nil
    redirect_to '/'
  end

private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_action :authorize, only: [:map]
  
  def index
  end

  def about
  end

  def map
    @rows = 6
    @columns = 12
  end

end

app/controllers/user_question_types_controller.rb
require 'json'

class UserQuestionTypesController < ApplicationController

  def index
    #session variable sets the key :map_state to the data passed through from ajax call
    #'should' be working, theres a 200 response with the data as string in the logs
    if session[:userQuestionTypes]
      render json: { userQuestionTypes: session[:userQuestionTypes]}
    else
      render json: { userQuestionTypes: ['simpleAddition'] }
    end
  end
  
  def create
    session[:userQuestionTypes] = JSON.parse(params[:userQuestionTypes])
    render json: session[:userQuestionTypes]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :destroy]
  def new
    if current_user
      redirect_to user_path(current_user)
    else
      @user = User.new
    end
  end

  def create
    if current_user
      redirect_to user_path(current_user)
    else
      @user = User.new(user_params)
    end
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You have successfully created an account"
      redirect_to user_path(current_user)
    else 
      flash[:error] = "Something weird happened"
      redirect_to '/signup'
    end
  end

  def show
    @caught_pokemons = @user.caught_pokemons.order("national_id ASC").page(params[:page]).per(10)
  end

  def destroy
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caught_pokemon_helper.rb
module CaughtPokemonHelper
end

app/helpers/mapstates_helper.rb
module MapstatesHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/caught_pokemons/show.html.erb
<div class="container">
  <div class="row show-grid br12 red text-white pokedex borderblack"> <!-- pokedex -->
    <div class="col-xs-6 show-grid borderright leftcolumn"> <!-- left column -->
      <div class="row padding red br12"> <!-- buttons above ash -->
        <div class="col-xs-2 ">
          <%= image_tag asset_path('water.png'), class: "pokedex-picture img-responsive img-circle borderblack" %>
        </div>
        <div class="col-xs-1">
          <button class="btn btn-xs br12 borderblack btn-danger" id="no-outline">&nbsp;</button>
        </div>
        <div class="col-xs-1">
          <button class="btn btn-xs br12 borderblack btn-warning" id="no-outline">&nbsp;</button>
        </div>
        <div class="col-xs-1">
          <button class="btn btn-xs br12 borderblack btn-success" id="no-outline">&nbsp;</button>
        </div>
      </div>
      <div class="row padding"> <!-- picture row -->
        <div class="col-xs-8 col-xs-offset-2 padding">
          <div class="row gray padding borderblack">
            <div class="col-xs-8 col-xs-offset-2 padding">
              <div class="row blue padding borderblack br12">
                <div class="col-xs-10 col-xs-offset-1">
                  <%= image_tag "pokemon/" + @pokemon.sprite, class: "img-responsive" %>
                </div>
              </div>
            </div>
          </div>
        </div>        
      </div>
      <div class="row"> <!-- user info row -->
        <div class="col-xs-10 col-xs-offset-1">
          <h3 class="text-center"><%= @caught_pokemon.name %></h3>
          <h4>Caught <%= time_ago_in_words(@caught_pokemon.created_at)%> ago</h4>
        </div>
      </div>
      <div class="row padding"> <!-- question row -->
        <%= link_to user_path(@caught_pokemon.user) do %>
          <div class="col-xs-10 col-xs-offset-1 borderblack text-black green padding hoverGreen">
            <h4 class="text-center">
              Back to your PokéDex
            </h4>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-xs-6 show-grid borderleft rightcolumn"> <!-- right column -->
      <div class="row show-grid padding20 br12">
        <div class="col-xs-10 col-xs-offset-1 green borderblack text-black">
          <div class="row borderbottom"> <!-- species -->
            <div class="col-xs-12 text-center">
              <h4><%= @pokemon.species %></h4>
            </div>
          </div>
          <div class="row borderbottom"> <!-- national id -->
            <div class="col-xs-6">
              <h5 class="text-right"><strong>
                National ID:
              </strong></h5>
            </div>
            <div class="col-xs-6">
              <h5>
                <%= @pokemon.national_id %>
              </h5>
            </div>
          </div>
          <div class="row borderbottom"> <!-- types -->
            <div class="col-xs-6">
              <h5 class="text-right"><strong>
                Type<% if @pokemon.pokemon_type2 %>s<% end %>:
              </strong></h5>
            </div>
            <div class="col-xs-6">
              <h5>
                <%= @pokemon.pokemon_type1.titleize %><% if @pokemon.pokemon_type2 %>, <%= @pokemon.pokemon_type2.titleize %><% end %>
              </h5>
            </div>
          </div>
          <div class="row borderbottom"> <!-- attack -->
            <div class="col-xs-6">
              <h5 class="text-right"><strong>
                Attack:
              </strong></h5>
            </div>
            <div class="col-xs-6">
              <h5>
                <%= @pokemon.attack %>
              </h5>
            </div>
          </div>
          <div class="row borderbottom"> <!-- defense -->
            <div class="col-xs-6">
              <h5 class="text-right"><strong>
                Defense:
              </strong></h5>
            </div>
            <div class="col-xs-6">
              <h5>
                <%= @pokemon.defense %>
              </h5>
            </div>
          </div>
          <div class="row borderbottom"> <!-- special attack -->
            <div class="col-xs-6">
              <h5 class="text-right"><strong>
                Special Attack:
              </strong></h5>
            </div>
            <div class="col-xs-6">
              <h5>
                <%= @pokemon.sp_attack %>
              </h5>
            </div>
          </div>
          <div class="row borderbottom"> <!-- special defense -->
            <div class="col-xs-6">
              <h5 class="text-right"><strong>
                Special Defense:
              </strong></h5>
            </div>
            <div class="col-xs-6">
              <h5>
                <%= @pokemon.sp_defense %>
              </h5>
            </div>
          </div>
          <div class="row borderbottom"> <!-- speed -->
            <div class="col-xs-6">
              <h5 class="text-right"><strong>
                Speed:
              </strong></h5>
            </div>
            <div class="col-xs-6">
              <h5>
                <%= @pokemon.speed %>
              </h5>
            </div>
          </div>
          <% if @pokemon.evolution %> evolution
            <div class="row borderbottom">
              <div class="col-xs-5">
                <h5 class="text-right"><strong>
                  Evolves Into:
                </strong></h5>
              </div>
              <div class="col-xs-6">
                <h5>
                  <%= @pokemon.evolution %>
                </h5>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <% if current_user.id == @caught_pokemon.user_id %>
      <div class="row">
        <div class="col-xs-3 col-xs-offset-3">
          <%= link_to 'Release Pokemon', caught_pokemon_path(@caught_pokemon), id: "no-outline", class: "btn borderblack btn-warning", method: :delete %>
        </div>
      </div>  
      <% end %>          
    </div>
  </div>
</div>
<audio autoplay="autoplay">
  <source src="/assets/<%= @caught_pokemon.national_id %>.mp3" type="audio/mpeg">
</audio>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pokemath</title>
  
  <%= favicon_link_tag 'favicon.ico' %>
  <link rel="shortcut icon" href="app/assets/images/favicon.ico"/>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href='//cdnjs.cloudflare.com/ajax/libs/animate.css/3.1.1/animate.min.css' rel='stylesheet' />
</head>
<body class="<%= controller_name %> <%= action_name %>">

  <%= render "partials/flashMsg" %>
  <%= render "partials/navbar" %>
  <%= render "partials/question_type" %>

  <%= yield %>

  <script src='//cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js'></script>
  <script src='//cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.js'></script>
</body>
</html>

app/views/partials/_flashMsg.html.erb
<% flash.each do |type, msg| %>
  <div class='alert <%= type == 'error' ? 'alert-danger' : 'alert-success'%> alert-messages'>
    <div class='container-fluid text-center'>
      <%= msg %>
    </div>
  </div>
<% end %>

app/views/partials/_navbar.html.erb
<nav id="topNav" class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand " href="/"><%= image_tag ("pika.gif"), class: "img-responsive pika-gif" %></a>
    </div>
    <div class="navbar-collapse collapse" id="bs-navbar">
      <ul class="nav navbar-nav pull-left">
        <li>
          <a href="#" data-target="#instrucModal" data-toggle="modal">Instructions</a>
        </li>
        <li>
          <%= link_to "About", "/about" %>
        </li>
        <% if current_user %>
          <% unless controller_name == "pokemons" && action_name == "show" %>
            <li>
              <%= link_to "Questions", "javascript:void(0)", data: { toggle: "modal", target: "#questionModal" } %>
            </li>
          <% end %>
        <% end %>
      </ul>
    <div class="navbar-collapse collapse" id="bs-navbar"> 
      <ul class="nav navbar-nav pull-right">
        <% if current_user %>
        <li>
          <%= link_to "Play Game!", "/map" %>
        </li>
          <li>
             <%= link_to "PokéDex", user_path(current_user) %>
          </li>
          <li> 
            <%= link_to "Logout", "/logout" %>
          </li>
        <% else %>
          <li>
            <%= link_to "Login", "/login" %> 
          </li>
          <li> 
            <%= link_to "Signup", "/signup" %>
          </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

<!-- Modal -->
<div id="instrucModal" class="modal fade" role="dialog">
  <div class="modal-dialog"> 
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;
        </button>
        <h4 class="modal-title header-font" >Instructions</h4>
      </div>
      <div class="modal-body">
        <p class="modal-instructions">Move around the map with the following keys:</p>
        <p class="modal-instructions">J - Left</p>
        <p class="modal-instructions">K - Down</p>
        <p class="modal-instructions">L - Right</p>
        <p class="modal-instructions">I - Up</p>
        <br>
        <p class="modal-instructions">Move towards any pokemon for a chance to catch it!</p>
        <p class="modal-instructions">When engaged in battle, use J, K or L to select the correct answer.</p>
      </div>
    </div>
  </div>
</div>

app/views/partials/_navbarPartial.html.erb
<nav id="topNav" class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand " href="/"><%= image_tag ("pika.gif"), class: "img-responsive pika-gif" %></a>
    </div>
    <div class="navbar-collapse collapse" id="bs-navbar">
      <ul class="nav navbar-nav pull-left">
        <li>
          <a href="#" data-target="#instrucModal" data-toggle="modal">Instructions</a>
        </li>
        <li>
          <%= link_to "About", "/about" %>
        </li>
      </ul>
    <div class="navbar-collapse collapse" id="bs-navbar"> 
      <ul class="nav navbar-nav pull-right">
        <% if current_user %>
        <li>
          <%= link_to "Play Game!", "/map" %>
        </li>
          <li>
             <%= link_to "PokéDex", user_path(current_user) %>
          </li>
          <li> 
            <%= link_to "Logout", "/logout" %>
          </li>
        <% else %>
          <li>
            <%= link_to "Login", "/login" %> 
          </li>
          <li> 
            <%= link_to "Signup", "/signup" %>
          </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

<!-- Modal -->
<div id="instrucModal" class="modal fade" role="dialog">
  <div class="modal-dialog"> 
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;
        </button>
        <h4 class="modal-title header-font" >Instructions</h4>
      </div>
      <div class="modal-body">
        <h5 class="header-font">How to play</h5>
        <p>Move around the map with the keys J K L I</p>
        <p>J Left</p>
        <p>K Down</p>
        <p>L Right</p>
        <p>I Up</p>
        <p>Move towards any pokemon for a chance to catch it!</p>
        <p>When engaged in battle, use J, K or L to select the correct answer </p>
      </div>
    </div>
  </div>
</div>

app/views/partials/_question_type.html.erb
<!-- Modal -->
<div class="modal fade" id="questionModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title header-font" id="myModalLabel">Choose Your Question Types</h4>
      </div>
      <div class="modal-body">
        <form>
          <div class="checkbox">
            <label class="modal-label">
              <input type="checkbox" name="simpleAddition">Simple Addition
            </label>
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox" name="ddAddition">Double Digit Addition
            </label>
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox" name="simpleSubtraction">Simple Subtraction
            </label>
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox" name="ddSubtraction">Double Digit Subtraction
            </label>
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox" name="simpleMultiplication">Simple Multiplication
            </label>
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox" name="ddMultiplication">Double Digit Multiplication
            </label>
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox" name="simpleDivision">Simple Division
            </label>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-success btn-login-signup" id="save-question">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/pokemons/show.html.erb
<div class="container game-screen">
  <div class="row" id="battle-screen">
    <div class="col-xs-8 battle-toggle" id="battle-encounter">
      <div class="well">
        <h1 class="text-center"><strong>You've encountered a <%= @pokemon.species %></strong></h1>
        <br>
        <h3>Answer all five questions correctly to catch <%= @pokemon.species %>.</h3>
        <h3>Be sure to answer fast enough, or <%= @pokemon.species %> will run away!</h3>
        <br>
        <h2 class="text-center">Press [spacebar] to begin.</h2>
      </div>
    </div>
    <div class="col-xs-8 battle-toggle" id="battle-questions">
      <div class="row"> <!-- timer -->
        <div class="col-xs-12">
          <h1 id="hidden-timer"><%= @pokemon.catch_rate / 10 %></h1>
          <h1 class="text-center blink" id="timer">Hurry up!</h1>
          <br>
        </div>
      </div>
      <div class="well">
        <div class="row"> <!-- problem# -->
          <div class="col-xs-12">
            <h1 class="text-center"><strong>Problem #<span id="problem-number"></span></strong></h1>
          </div>
        </div>
        <div class="row"> <!-- question -->
          <div class="col-xs-12">
            <br>
            <h1 class="text-center"><strong><span id="num1"></span> <span id="operation"></span> <span id="num2"></span> =</strong></h1>
            <br>
          </div>
        </div>
        <div class="row"> <!-- answers -->
          <div class="col-xs-4">
            <h1 class="text-center"><span id="choice1"></span></h1>
          </div>
          <div class="col-xs-4">
            <h1 class="text-center"><span id="choice2"></span></h1>
          </div>
          <div class="col-xs-4">
            <h1 class="text-center"><span id="choice3"></span></h1>
          </div>
        </div>
        <div class="row"> <!-- keys -->
          <div class="col-xs-4">
            <h1 class="text-center">J</h1>
          </div>
          <div class="col-xs-4">
            <h1 class="text-center">K</h1>
          </div>
          <div class="col-xs-4">
            <h1 class="text-center">L</h1>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-8 battle-toggle" id="battle-caught">
      <div class="well">
        <h1 class="text-center"><strong>You've caught <%= @pokemon.species %>!</strong></h1>
        <br>
        <h2>Give your <%= @pokemon.species %> a name and save him to your PokeDex.</h2>
        <br>
        <%= form_for @caught_pokemon do |f| %>
          <div class="form-group">
            <%= f.text_field :name, class: "form-control", id: "pokemon-name-field", placeholder: "Enter your pokemon name" %>
          </div>
          <%= f.hidden_field :pokemon_id, value: @pokemon.id %>
          <%= f.hidden_field :national_id, value: @pokemon.national_id %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <div class="form-group">
            <%= f.submit "Save to PokeDex", class: "btn btn-block btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-xs-8 battle-toggle" id="battle-escaped">
      <div class="well">
        <h1 class="text-center"><strong><%= @pokemon.species %> ran away...</strong></h1>
        <br>
        <h2 class="text-center">Press [spacebar] to return to the map.</h2>
      </div>
    </div>
    <div class="col-xs-4"> <!-- pokemon -->
      <div class="row"> <!-- progress bar -->
        <div class="col-xs-12 pokemon-status">
          <h5><%= @pokemon.species.upcase %> <span class="pull-right"><strong><i class="<% if rand(2) == 1 %>ion-male<% else %>ion-female<% end %>"></i></strong>&nbsp;LV<%= rand(50) %></span></h5>
          <div class="progress">
            <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" id="hp">
            </div>
          </div>
        </div>
      </div>
      <div class="row"> <!-- pokemon sprite -->
        <div class="col-xs-12">
          <%= image_tag "pokemon/"+@pokemon.sprite, class: "battle-pokemon img-responsive" %>
        </div>
      </div>
      <div class="row"> <!-- I choose you... -->
        <div class="col-xs-10 col-xs-offset-1" id="choose-you">
          <h1>I choose you, <span id="answer-choice"></span>!</h1>
        </div>
      </div>
    </div>
  </div>
</div>
<audio autoplay="autoplay">
  <source src="/assets/battle.mp3" type="audio/mpeg">
</audio>

app/views/site/index.html.erb
<header>
  <%= video_tag (["theme.mp4#t=0,50"]), autoplay: '', loop: true, type: 'video/mp4', id: "video-background" %>
  <div class="header-content">
    <h1 class="cursive wow flipInX text-center"><sub class="big-p">P</sub>oKéMaTH</h1>
    <h4 class="text-center">Gotta solve 'em all!</h4>
    <p class="text-center">
      <%= link_to "Signup now!", signup_path, class: "btn btn-lg btn-primary btn-landing" %>
    </p>
  <a href="#" class="mute  pull-right"><i class="ion-ios-volume-high on"></i></a>
  </div>
</header>

app/views/site/map.html.erb
<div class="container outer-container game-screen">
  <div class="container" id="game-map">
    <% @rows.times do |i| %>
      <div class="row">
        <% @columns.times do |j| %>
          <div class="col-xs-1 game-tile" data-row"<%= i+1 %>" data-col="<%= j+1 %>" id="r<%= i+1 %>c<%= j+1 %>">
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<audio autoplay="autoplay">
  <source src="/assets/map.mp3" type="audio/mpeg">
</audio>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h1 class="signup-login text-center">Sign Up!</h1>
    <hr>
    <%= form_for @user do |f| %>
      <div class="form-group">
        <%= f.label :username %>:
        <%= f.text_field :username, class: "form-control", placeholder: "Please enter your username", autofocus: true  %>
      </div>
      <div class="form-group">
        <%= f.label :password %>:
        <%= f.password_field :password, class: "form-control", placeholder: "Must be at least 6 characters" %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, "Password Confirmation" %>
        <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm password" %>
      </div>
      <div class="form-group">
        <%= f.submit "Sign Up", class: "btn btn-block btn-success btn-login-signup" %>
      </div>
    <% end %>
    <p>Already have an account? <%= link_to "Click here", login_path, class: "click-here" %> to log in.</p>
  </div>
</div>